language: node_js
node_js:
    - 10
    - 9
    - 8

script:
  - npm run lint
  - npm run build
  - npm run coverage
  - npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: required

services:
  - docker

deploy:
    provider: script
    script: npm run docker-ci
    skip_cleanup: true
    on:
        node: '8'
        tags: true
        all_branches: false

